Detect C compiler.
A basic Debian system doesn't have a C compiler.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12,6 +12,16 @@
 # Other settings: LTO, PGO?  Consider moving prefix, LTO, PGO to build and
 # install steps.
 
+log() {
+  echo "$0: $@" 2>&1
+}
+
+die() {
+  echo "$0 ERROR: $@" 2>&1
+  exit 1
+}
+
+
 # Default value is /usr/bin/oil.  The user might want to change it to
 # /usr/local/bin/oil or $HOME/bin/oil.
 FLAG_prefix='/usr/bin'
@@ -25,7 +35,6 @@ while true; do
     --help)
       # TODO: Fill out help
       echo HELP
-      exit 2
       ;;
 
     --with-readline)
@@ -39,30 +48,25 @@ while true; do
       ;;
     --prefix)
       if test $# -eq 1; then
-        echo "--prefix requires an argument"
-        exit 2
+        die "--prefix requires an argument"
       fi
       shift
       FLAG_prefix=$1
       ;;
     *)
-      echo 1>&2 "Invalid argument '$1'"
-      return 2
+      die "Invalid argument '$1'"
       ;;
   esac
   shift
 done
 
-
 # Write a shell script to standard out with variables, or fail.
-
 detect_readline() {
   if cc build/detect-readline.c -l readline -o /dev/null; then
     echo 'HAVE_READLINE=1'
   else
     if test "$FLAG_with_readline" = 1; then
-      echo 1>&2 'FATAL: --with-readline was passed but readline was not detected on the system.'
-      exit 1
+      die 'readline was not detected on the system (--with-readline passed).'
     fi
     echo 'HAVE_READLINE=0'
   fi
@@ -70,15 +74,19 @@ detect_readline() {
   echo "PREFIX=$FLAG_prefix"
 }
 
-
 # Another way of working: set detected-config.mk ?
 # And set the default target as oil_readline, oil_no_readline, oil_lto,
 # oil_pgo, etc.?
 main() {
+  if ! cc build/detect-cc.c -o /dev/null; then
+    die "Couldn't compile a basic C program (cc not installed?)"
+  fi
+
   # The makefile or shell script will 'source detected-config.sh'?  And then it
   # can pass -D to the compiler?
   local out=detected-config.sh
   detect_readline > $out
+  log "Wrote $out"
 }
 
 main "$@"
